# https://aws.amazon.com/jp/blogs/compute/announcing-ruby-support-for-aws-lambda/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'shuffle lunch group'

Resources:
  GetShuffleLunchUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/shuffle_lunch_group_lambda_function.lambda_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref RubyExampleDDBTable
      Environment:
        Variables:
          DDB_TABLE: !Ref RubyExampleDDBTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/users'
            Method: get

  RubyExampleDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  GetShuffleLunchUsersFunction:
    Description: GET all shuffle_lunch_users Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetShuffleLunchUsersFunction
      - Arn

