# https://aws.amazon.com/jp/blogs/compute/announcing-ruby-support-for-aws-lambda/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'shuffle lunch group'

Resources:
  PostShuffleLunchCandidatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/candidate_lambda_function.create_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref shuffleLunchCandidateTable
      Environment:
        Variables:
          CANDIDATE_TABLE: !Ref shuffleLunchCandidateTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/candidate'
            Method: post

  BulkCreateShuffleLunchCandidatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/candidate_lambda_function.bulk_create_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref shuffleLunchCandidateTable
      Environment:
        Variables:
          CANDIDATE_TABLE: !Ref shuffleLunchCandidateTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/bulk_create_candidates'
            Method: post

  AssignShuffleLunchCandidatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/candidate_lambda_function.assign_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref shuffleLunchCandidateTable
      Environment:
        Variables:
          CANDIDATE_TABLE: !Ref shuffleLunchCandidateTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/assign_candidate'
            Method: post

  shuffleLunchCandidateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "shuffleLunchCandidateTable"
      AttributeDefinitions:
        -
          AttributeName: "rotation_id"
          AttributeType: "N"
        -
          AttributeName: "user_email"
          AttributeType: "S"
        -
          AttributeName: "lunch_group"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "rotation_id"
          KeyType: "HASH"
        -
          AttributeName: "user_email"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        -
          IndexName: "candidateGSI_1"
          KeySchema:
            -
              AttributeName: "lunch_group"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

Outputs:
  PostShuffleLunchCandidatesFunction:
    Description: POST shuffle_lunch_candidates Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PostShuffleLunchCandidatesFunction
      - Arn
  BulkCreateShuffleLunchCandidatesFunction:
    Description: POST create bulk shuffle_lunch_candidates Lambda Function ARN
    Value:
      Fn::GetAtt:
      - BulkCreateShuffleLunchCandidatesFunction
      - Arn
  AssignShuffleLunchCandidatesFunction:
    Description: POST assign shuffle_lunch_candidates Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AssignShuffleLunchCandidatesFunction
      - Arn
