# https://aws.amazon.com/jp/blogs/compute/announcing-ruby-support-for-aws-lambda/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'shuffle lunch group'

Resources:
  GetShuffleLunchUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/shuffle_lunch_group_lambda_function.lambda_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref shuffleLunchUserTable
      Environment:
        Variables:
          DDB_TABLE: !Ref shuffleLunchUserTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/users'
            Method: get

  shuffleLunchUserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: email
        Type: String
      TableName: "shuffleLunchUserTable"

  shuffleLunchImplementationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "shuffleLunchImplementationTable"
      AttributeDefinitions:
        -
          AttributeName: "rotation_id"
          AttributeType: "N"
        -
          AttributeName: "shuffle_lunch_group_id"
          AttributeType: "S"
        -
          AttributeName: "user_email"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "shuffle_lunch_group_id"
          KeyType: "HASH"
        -
          AttributeName: "user_email"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "shuffleLunchImplementationTableGSI1"
          KeySchema:
            -
              AttributeName: "rotation_id"
              KeyType: "HASH"
            -
              AttributeName: "user_email"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "shuffle_lunch_group_id"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

Outputs:
  GetShuffleLunchUsersFunction:
    Description: GET all shuffle_lunch_users Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetShuffleLunchUsersFunction
      - Arn

