# https://aws.amazon.com/jp/blogs/compute/announcing-ruby-support-for-aws-lambda/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'shuffle lunch group'

Resources:
  PostShuffleLunchCandidatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/candidate_lambda_function.create_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref shuffleLunchCandidateTable
      Environment:
        Variables:
          CANDIDATE_TABLE: !Ref shuffleLunchCandidateTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/candidate'
            Method: post

  shuffleLunchCandidateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "shuffleLunchCandidateTable"
      AttributeDefinitions:
        -
          AttributeName: "rotation_id"
          AttributeType: "N"
        -
          AttributeName: "user_email"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "rotation_id"
          KeyType: "HASH"
        -
          AttributeName: "user_email"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  shuffleLunchImplementationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "shuffleLunchImplementationTable"
      AttributeDefinitions:
        -
          AttributeName: "rotation_id"
          AttributeType: "N"
        -
          AttributeName: "shuffle_lunch_group_id"
          AttributeType: "S"
        -
          AttributeName: "user_email"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "shuffle_lunch_group_id"
          KeyType: "HASH"
        -
          AttributeName: "user_email"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "shuffleLunchImplementationTableGSI1"
          KeySchema:
            -
              AttributeName: "rotation_id"
              KeyType: "HASH"
            -
              AttributeName: "user_email"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "shuffle_lunch_group_id"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

Outputs:
  PostShuffleLunchCandidatesFunction:
    Description: POST shuffle_lunch_candidates Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PostShuffleLunchCandidatesFunction
      - Arn

