# https://aws.amazon.com/jp/blogs/compute/announcing-ruby-support-for-aws-lambda/
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'shuffle lunch group'

Resources:
  GetShuffleLunchUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/shuffle_lunch_group_lambda_function.lambda_handler
      Runtime: ruby2.5
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref shuffleLunchUserTable
      Environment:
        Variables:
          DDB_TABLE: !Ref shuffleLunchUserTable
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/users'
            Method: get

  shuffleLunchUserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: email
        Type: String
      TableName: "shuffleLunchUserTable"

  shuffleLunchImplementationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "shuffleLunchImplementationTable"
      AttributeDefinitions:
        -
          AttributeName: "Album"
          AttributeType: "S"
        -
          AttributeName: "Artist"
          AttributeType: "S"
        -
          AttributeName: "Sales"
          AttributeType: "N"
        -
          AttributeName: "NumberOfSongs"
          AttributeType: "N"
      KeySchema:
        -
          AttributeName: "Album"
          KeyType: "HASH"
        -
          AttributeName: "Artist"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "myGSI"
          KeySchema:
            -
              AttributeName: "Sales"
              KeyType: "HASH"
            -
              AttributeName: "Artist"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
        -
          IndexName: "myGSI2"
          KeySchema:
            -
              AttributeName: "NumberOfSongs"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Album"
              - "Artist"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
      LocalSecondaryIndexes:
        -
          IndexName: "myLSI"
          KeySchema:
            -
              AttributeName: "Album"
              KeyType: "HASH"
            -
              AttributeName: "Sales"
              KeyType: "RANGE"
          Projection:
            NonKeyAttributes:
              - "Artist"
              - "NumberOfSongs"
            ProjectionType: "INCLUDE"

Outputs:
  GetShuffleLunchUsersFunction:
    Description: GET all shuffle_lunch_users Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetShuffleLunchUsersFunction
      - Arn

